#!/bin/sh

# Notify me with notify-send if my battery is below 25%.
# You can set this to run via cron.

[ "$(cat /sys/class/power_supply/BAT0/status)" = "Charging" ] && exit

[ "$(cat /sys/class/power_supply/BAT0/capacity)" -lt 5 ] &&
betterlockscreen -s && exit

[ "$(cat /sys/class/power_supply/BAT0/capacity)" -lt 25 ] &&
export dbus_session_bus_address=unix:path=/run/user/1002/bus &&
notify-send -u critical "battery critically low."
